/**
*@file
*@brief     ab281项目配置文件
*@details
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_AB281A_H_
#define _UTE_PROJECT_CONFIG_AB281A_H_

#define DEFAULT_BLE_DEV_NAME "romio"
#define UTE_SW_VERSION "ABE012V000026"

/*! 指定资源路径,如果不定义则使用对应项目号的路径,wang.luo 2025-01-07 */
#define UTE_UI_CONFIG_PATCH "ABE012"

/* 睡眠数据采样支持 zn.zeng 2021-12-29*/
#define UTE_MODULE_SLEEP_SAMPLE_DATA_SUPPORT 1
/*gesnsor 采集原始数据*/
#define APP_DBG_GSENSOR_DATA 0

#define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 0
#define UTE_DRV_QSPI_FOR_SCREEN_SUPPORT 1

#define UTE_DRV_TFT_S240X284_NV3030B_HY201068AVC_QSPI_SUPPORT 0
#define DRV_BOE_S240X284_I183_JD9853_WV018LZQ_QSPI_SUPPORT 0
#define DRV_BOE_S240X296_I183_JD9853_WV018LZQ_QSPI_SUPPORT 1
#define UTE_DRV_TFT_S240X284_NV3030B_ZD183G1196_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S360X360_NV3030B_HY139071A_QSPI_SUPPORT 0
#define UTE_DRV_TFT_S240X296NV3030B_ZD183G1196_QSPI_SUPPORT 0

// #define DEFAULT_TP_UPDATE_VER_CHECKOUT_OPEN  0

/*! 屏最大亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MAX 100

/*! 屏最小亮度百分比 dengli.lu, 2021-10-29  */
#define DEFAULT_BACK_LIGHT_PERCENT_MIN 20

/*! 调节屏亮度时增加或者减少的百分比 dengli.lu, 2021-10-29  */
#define BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE 20

/*! 默认背光百分比zn.zeng, 2021-09-24  */
#define DEFAULT_SCREEN_BACKLIGHT_PERCENT    (BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE*3)

#define UTE_DRV_GSENSOR_SC7A20H_SUPPORT 1

#define UTE_TASK_USER_SUPPORT 1

#define UTE_BINDING_QRENCODE_LINK "https://app.uteasy.com/download/romio-c-.html"

/*! 抬手亮屏参数 zn.zeng, 2021-10-22  */
#define ROLLOVER_HAND_SCREEN_X_MIN  -40
#define ROLLOVER_HAND_SCREEN_X_MAX  140
#define ROLLOVER_HAND_SCREEN_Y_MIN  -46
#define ROLLOVER_HAND_SCREEN_Y_MAX  40
#define ROLLOVER_HAND_SCREEN_Z_MIN  -136
#define ROLLOVER_HAND_SCREEN_Z_MAX  128
#define ROLLOVER_HAND_SCREEN_ACC_DIFF_VALUE  20

#define QUICK_SWITCH_NOT_DISTURB_SUPPORT 1
#define QUICK_SWITCH_ANTILOST_SUPPORT   1
#define QUICK_SWITCH_DISPLAY_TIME_SUPPORT   1
#define QUICK_SWITCH_FINDBAND_SUPPORT 0
#define QUICK_SWITCH_TURNTHEWRIST_SUPPORT 1
#define QUICK_SWITCH_SHOCK_TIME_SUPPORT    1
#define QUICK_SWITCH_LOCAL_WURAO_SET_TIME_SUPPORT 1

/*! PWRKEY,wang.luo 2024-12-03 */
#define UTE_DRV_PWRKEY_SUPPORT 1
/*! PWRKEY按键最大数量,wang.luo 2024-12-03 */
#define UTE_DRV_PWRKEY_MAX_CNT 1

/*! 心率最大最小值数字显示跟随柱状图中的最大最小值 xjc, 2022-01-17  */
#define UTE_HEART_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT 1

/*! 新工厂测试,xjc 2022-02-09*/
#define UTE_MODULE_NEW_FACTORY_TEST_SUPPORT 1
#define UTE_MODULE_LOCK_SCREEN_SUPPORT 1
#if UTE_MODULE_NEW_FACTORY_TEST_SUPPORT
#define UTE_MODULE_SCREENS_NEW_FACTORY_MODE_SELECT_SUPPORT 1
#define UTE_MODULE_SCREENS_NEW_FACTORY_AGING_TEST_SUPPORT 1
#define UTE_MODULE_SCREENS_NEW_FACTORY_MODULE_TEST_SUPPORT 1

#define UTE_MODULE_NEW_FACTORY_TEST_JUST_HEART_CHECK_LIGHT_SUPPORT  0 //开机显示心率漏光界面
#define UTE_MODULE_NEW_FACTORY_MODULE_TEST_ALLOW_RETEST_SUPPORT 1 //fail项目允许在列表中点击重新测试
#define UTE_MODULE_NEW_FACTORY_AGING_REPORT_SUPPORT 0 //老化测试生成测试报告
#define UTE_MODULE_NEW_FACTORY_MODULE_4X5_TP_TEST_SUPPORT 1 //4*5 = 20宫格TP触摸测试
#define UTE_MODULE_NEW_FACTORY_MODULE_4X5_TP_TOTAL 20
// #define UTE_MODULE_NEW_FACTORY_MODULE_MAX 13
#define UTE_MODULE_NEW_FACTORY_MODULE_END_RESET_SUPPORT 1 //模块测试结束之后复位重启
#define UTE_MODULE_NEW_FACTORY_MODULE_HEART_CHECK_LIGHT_SUPPORT 0 //新工厂模块测试默认有心率漏光测试
#define UTE_DRV_NEW_FACTORY_TEST_BATTERY_CE_AUTH_ALLOW_TEMPERATURE 58.0f //工厂测试温度限制
#define UTE_DRV_NEW_FACTORY_TEST_BATTERY_CE_AUTH_NOT_ALLOW_TEMPERATURE 60.0f
#define UTE_MODULE_NEW_FACTORY_MODE_SELECT_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_AGING_TEST_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_MODULE_TEST_SCREENS_STRING_ENLARGEMENT 2
#define UTE_MODULE_NEW_FACTORY_TEST_CHAR_EN_SUPPORT  1
#endif

/* 电池容量 zn.zeng 2022-01-07*/
#define UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH      200 //mAh

/* 电池曲线 zn.zeng 2022-01-03*/
#define UTE_DRV_BATTERY_000      3472
#define UTE_DRV_BATTERY_010      3682
#define UTE_DRV_BATTERY_020      3660
#define UTE_DRV_BATTERY_030      3690
#define UTE_DRV_BATTERY_040      3720
#define UTE_DRV_BATTERY_050      3750
#define UTE_DRV_BATTERY_060      3790
#define UTE_DRV_BATTERY_070      3850
#define UTE_DRV_BATTERY_080      3900
#define UTE_DRV_BATTERY_090      3920
#define UTE_DRV_BATTERY_100      4130

#define UTE_DRV_TP_X_AXIS_EXCHANGE 0 // 交换X轴左右坐标
#define UTE_DRV_TP_Y_AXIS_EXCHANGE 0 // 交换Y轴上下坐标

/*! 一级界面默认排序,wang.luo 2024-11-16 */
#define UTE_CUI_SCREEN_TBL_SORT_CNT_DEFAULT 8
// #define UTE_CUI_SCREEN_TBL_SORT_ARRAY_DEFAULT {FUNC_CLOCK, FUNC_ACTIVITY, FUNC_BLOOD_OXYGEN, FUNC_HEARTRATE, FUNC_SLEEP, FUNC_WEATHER, FUNC_BT, FUNC_COMPO_SELECT}
#define UTE_CUI_SCREEN_TBL_SORT_ARRAY_DEFAULT {FUNC_CLOCK, FUNC_ECIG_SET_POWER,FUNC_ECIG_VPAE_SUB, FUNC_ALARM_CLOCK, FUNC_CALCULATOR,  FUNC_BT, FUNC_WEATHER,FUNC_COMPO_SELECT}
/*! 默认表盘索引 zn.zeng, 2021-10-25  */
#define DEFAULT_WATCH_INDEX 0
/*! 最大表盘数量，不包括在线表盘 zn.zeng, 2021-10-23  */
#define UTE_MODULE_SCREENS_WATCH_CNT_MAX 4
/*! 表盘排序地址数组,wang.luo 2024-11-26 */
// #define UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS {UI_BUF_DIALPLATE_D17312001_BIN, UI_BUF_DIALPLATE_D17196001_BIN, UI_BUF_DIALPLATE_D17195001_BIN, UI_BUF_DIALPLATE_D17194001_BIN, UI_BUF_DIALPLATE_BTF_BIN, UI_BUF_DIALPLATE_CUBE_BIN}

#define UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS { UI_BUF_DIALPLATE_FACEWATCH2_BIN,  UI_BUF_DIALPLATE_FACEWATCH3_BIN, UI_BUF_DIALPLATE_BTF_BIN, UI_BUF_DIALPLATE_CUBE_BIN}
#define UTE_WATCHS_BUTTERFLY_DIAL_SUPPORT 1 // 使用蝴蝶表盘
#define UTE_WATCHS_CUBE_DIAL_SUPPORT 1      // 使用立方体表盘
#define UTE_WATCHS_DIALPLATE_BTF_INDEX 2    // 蝴蝶表盘索引
#define UTE_WATCHS_DIALPLATE_CUBE_INDEX 3   // 立方体表盘索引

/*! SOS联系人拨号功能,xjc 2022-07-06  */
#define UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT 1

#define GUI_SCREEN_SIZE_240X284RGB_I330001_SUPPORT      1
#define GUI_MODULE_WRIST_SUPPORT      0
#define UTE_ALARM_NOTDISTURB_ALLOW_MOTOR_VIBRATION_SUPPORT 1 //勿扰模式闹钟开启马达震动

#if UTE_DRV_TFT_S360X360_NV3030B_HY139071A_QSPI_SUPPORT
#define UTE_DRV_SCREEN_WIDTH 360
#define UTE_DRV_SCREEN_HEIGHT 360
#define UTE_DRV_SCREEN_SHAPE 0
#elif UTE_DRV_TFT_S240X284_NV3030B_HY201068AVC_QSPI_SUPPORT
#define UTE_DRV_SCREEN_WIDTH 240
#define UTE_DRV_SCREEN_HEIGHT 296
#elif DRV_BOE_S240X296_I183_JD9853_WV018LZQ_QSPI_SUPPORT
#define UTE_DRV_SCREEN_WIDTH 240
#define UTE_DRV_SCREEN_HEIGHT 296
#endif

#define UTE_MODULE_SCREENS_POWERON_SUPPORT            1 //开机logo界面
#define UTE_MODULE_SCREENS_UP_MENU_SUPPORT            1 //上拉菜单
#define UTE_MODULE_SCREENS_DWON_MENU_SUPPORT          1 //下拉菜单
#define UTE_MODULE_SCREENS_LINK_MAN_SUPPORT           1 //联系人
#define UTE_MODULE_SCREENS_TIMER_SUPPORT              1 //计时器
#define UTE_MODULE_SCREENS_CAMERA_SUPPORT             1 //遥控拍照
#define UTE_MODULE_SCREENS_STOPWATCH_SUPPORT          1 //秒表
#define UTE_MODULE_SCREENS_VOICE_SUPPORT              1 //语音
#define UTE_MODULE_SCREENS_ALARM_SUPPORT              1 //闹钟
#define UTE_MODULE_SCREENS_SYNC_WATCH_ONLINE_SUPPORT  1 //在线表盘同步界面
#define UTE_MODULE_SCREENS_LOW_BATTERY_NOTIFY_SUPPORT 1 //低电提醒
#define UTE_MODULE_SCREENS_WEATHER_SUPPORT            1 //天气
#define xUTE_MODULE_SCREENS_GAME_SUPPORT               1 //游戏
#define UTE_MODULE_SCREENS_FIND_PHNOE_SUPPORT         1 //找手机
#define UTE_MODULE_SCREENS_RESFY_SUPPORT              1 //恢复出厂
#define UTE_MODULE_SCREENS_BLOOD_OXYGEN_SUPPORT       0 //血氧
#define UTE_MODULE_SCREENS_ACTIVITY_SUPPORT           0 //每日活动
#define UTE_MODULE_SCREENS_FLASHLIGHT_SUPPORT         1 //手电筒
#define UTE_MODULE_SCREENS_SPORT_SUPPORT              0 //运动
#define UTE_MODULE_SCREENS_LANGUAGE_SUPPORT           1 //语言
#define UTE_MODULE_SCREENS_BREATHE_SUPPORT            0 //呼吸
#define UTE_MODULE_SCREENS_HEARTRATE_SUPPORT          0 //心率
#define UTE_MODULE_SCREENS_STYLE_SUPPORT              1 //主题
#define UTE_MODULE_SCREENS_SLEEP_SUPPORT              0 //睡眠
#define UTE_MODULE_SCREENS_LIGHT_SUPPORT              1 //亮度调节
#define UTE_MODULE_SCREENS_MUSIC_SUPPORT              1 //音乐
#define UTE_MODULE_SCREENS_MESSAGE_SUPPORT            1 //信息
#define UTE_MODULE_SCREENS_CALL_SUPPORT               1 //电话
#define UTE_MODULE_SCREENS_SETTING_SUPPORT            1 //设置
#define UTE_MODULE_SCREENS_CALCULATOR_SUPPORT         1 //计算器
#define UTE_MODULE_SCREENS_RESTART_SUPPORT            1 //重启
#define UTE_MODULE_SCREENS_CALENDAER_SUPPORT          1 //日历
#define UTE_MODULE_SCREENS_CALENDAER_SUB_SUPPORT      1 //日历一级界面
#define UTE_MODULE_SCREENS_SCAN_SUPPORT               1 //二维码

/*! 支持的运动数量, xjc 2022-03-09  */
#define UTE_MODULE_SPORT_MAX_SPORT_NUM 25
#define UTE_MODULE_SPORT_RUNNING_SUPPORT                1 //跑步
#define UTE_MODULE_SPORT_BIKE_SUPPORT                   1 //骑行
#define UTE_MODULE_SPORT_JUMP_ROPE_SUPPORT              1 //跳绳
#define UTE_MODULE_SPORT_SWIMMING_SUPPORT               1 //游泳
#define UTE_MODULE_SPORT_BADMINTION_SUPPORT             1 //羽毛球
#define UTE_MODULE_SPORT_TABLE_TENNIS_SUPPORT           1 //乒乓球
#define UTE_MODULE_SPORT_TENNIS_SUPPORT                 1 //网球
#define UTE_MODULE_SPORT_CLIMBING_SUPPORT               1 //登山
#define UTE_MODULE_SPORT_WALKING_SUPPORT                1 //徒步
#define UTE_MODULE_SPORT_BASKETBALL_SUPPORT             1 //篮球
#define UTE_MODULE_SPORT_FOOTBALL_SUPPORT               1 //足球
#define UTE_MODULE_SPORT_BASEBALL_SUPPORT               1 //棒球（或垒球）
#define UTE_MODULE_SPORT_VOLLEYBALL_SUPPORT             1 //排球
#define UTE_MODULE_SPORT_CRICKET_SUPPORT                1 //板球
#define UTE_MODULE_SPORT_RUGBY_SUPPORT                  1 //橄榄球（或美式足球）
#define UTE_MODULE_SPORT_HOCKEY_SUPPORT                 1 //曲棍球
#define UTE_MODULE_SPORT_DANCE_SUPPORT                  1 //跳舞
#define UTE_MODULE_SPORT_SPINNING_SUPPORT               1 //动感单车
#define UTE_MODULE_SPORT_YOGA_SUPPORT                   1 //瑜伽
#define UTE_MODULE_SPORT_SIT_UP_SUPPORT                 1 //仰卧起坐
#define UTE_MODULE_SPORT_TREADMILL_SUPPORT              1 //跑步机
#define UTE_MODULE_SPORT_GYMNASTICS_SUPPORT             1 //体操
#define UTE_MODULE_SPORT_BOATING_SUPPORT                1 //划船
#define UTE_MODULE_SPORT_JUMPING_JACK_SUPPORT           1 //开合跳
#define UTE_MODULE_SPORT_FREE_TRAINING_SUPPORT          1 //自由训练

/*! 默认语言 zn.zeng, 2021-08-23  */
#ifndef DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE 0x02 //默认语言
#define SCREEN_TITLE_MULTIPLE_CHINESE_LANGUAGE_SUPPORT              0 //中文 1
#define SCREEN_TITLE_MULTIPLE_ENGLISH_LANGUAGE_SUPPORT              1 //英文 2
#define SCREEN_TITLE_MULTIPLE_KOREAN_LANGUAGE_SUPPORT               0 //韩文 3
#define SCREEN_TITLE_MULTIPLE_JAPANESE_LANGUAGE_SUPPORT             0 //日文 4
#define SCREEN_TITLE_MULTIPLE_GERMAN_LANGUAGE_SUPPORT               0 //德文 5
#define SCREEN_TITLE_MULTIPLE_SPANISH_LANGUAGE_SUPPORT              1 //西班牙文 6
#define SCREEN_TITLE_MULTIPLE_FRENCH_LANGUAGE_SUPPORT               1 //法文 7
#define SCREEN_TITLE_MULTIPLE_ITALIAN_LANGUAGE_SUPPORT              0 //意大利文 8
#define SCREEN_TITLE_MULTIPLE_PORTUGUESE_LANGUAGE_SUPPORT           0 //葡萄牙文 9
#define SCREEN_TITLE_MULTIPLE_ARABIC_LANGUAGE_SUPPORT               1 //阿拉伯文 A
#define SCREEN_TITLE_MULTIPLE_INDIA_LANGUAGE_SUPPORT                0 //India     B
#define SCREEN_TITLE_MULTIPLE_HINDI_LANGUAGE_SUPPORT                0 //印地语  C
#define SCREEN_TITLE_MULTIPLE_POLISH_LANGUAGE_SUPPORT               1 //波兰语  D
#define SCREEN_TITLE_MULTIPLE_RUSSIAN_LANGUAGE_SUPPORT              1 //俄语  E
#define SCREEN_TITLE_MULTIPLE_DUTCH_LANGUAGE_SUPPORT                0 //荷兰语 F
#define SCREEN_TITLE_MULTIPLE_TURKISH_LANGUAGE_SUPPORT              0 //土耳其语  10
#define SCREEN_TITLE_MULTIPLE_BENGALI_LANGUAGE_SUPPORT              0 //孟加拉语  11  Bengali
#define SCREEN_TITLE_MULTIPLE_URDU_LANGUAGE_SUPPORT                 0 //乌尔都语   12  Urdu
#define SCREEN_TITLE_MULTIPLE_INDONESUAN_LANGUAGE_SUPPORT           1 //印度尼西亚语（爪哇语）  13  Indonesian
#define SCREEN_TITLE_MULTIPLE_PUNJABI_LANGUAGE_SUPPORT              0 //旁遮普语  14   Punjabi
#define SCREEN_TITLE_MULTIPLE_THAI_LANGUAGE_SUPPORT                 0 //泰文  15   Thai
#define SCREEN_TITLE_MULTIPLE_CZECH_LANGUAGE_SUPPORT                0 //捷克语  16  Czech
#define SCREEN_TITLE_MULTIPLE_TRADITIONAL_CHINESE_LANGUAGE_SUPPORT  0 //繁体中文
#define SCREEN_TITLE_MULTIPLE_ROMANIAN_LANGUAGE_SUPPORT             0 //罗马尼亚语 limba 0x1B
#define SCREEN_TITLE_MULTIPLE_VIETNAMESE_LANGUAGE_SUPPORT           0 //越南语 0x63
#endif // DEFAULT_LANGUAGE

#endif//_UTE_PROJECT_CONFIG_AB281_H_
