/**
*@file
*@brief     项目配置文件
*@details   ute 项目总配置文件
*@author        zn.zeng
*@date        2024-03-22
*@version       v1.0
*/
#ifndef _UTE_PROJECT_CONFIG_H_
#define _UTE_PROJECT_CONFIG_H_

#define PROJECT_AB281_SUPPORT        0
#define PROJECT_AB281A_SUPPORT       0 /*! 同乐达 T8Z,TFT 240X284 NV3030B,CHIP_5691C_F,wang.luo 2025-01-06 */
#define PROJECT_AB281B_SUPPORT       0 /*! 整机 801, TFT 240x282 NV3030B,CHIP_5691C_F,wang.luo 2025-01-10 */
#define PROJECT_AB281C_SUPPORT       0 /*! , TFT 360x360 NV3030B,CHIP_5691C_F,quan.qi.cai 2025-01-21 */
#define PROJECT_ABE012_SUPPORT       1

#if PROJECT_AB281_SUPPORT
#include"ute_project_config_ab281.h"
#elif PROJECT_AB281A_SUPPORT
#include"ute_project_config_ab281a.h"
#elif PROJECT_AB281B_SUPPORT
#include"ute_project_config_ab281b.h"
#elif PROJECT_AB281C_SUPPORT
#include"ute_project_config_ab281c.h"
#elif PROJECT_ABE012_SUPPORT
#include"ute_project_config_abe012.h"
#endif
/** Log模块控制开关*/
#define UTE_MODULE_LOG_SUPPORT 1



/** 芯片选型 */
#define CHIP_5691G                      0           //QFN40
#define CHIP_5691C_F                    1           //QFN40
#define CHIP_5690G                      2           //QFN52
#define CHIP_5690F                      3           //QFN52

//芯片封装选择 5691G/5691C_F
#ifndef UTE_CHIP_PACKAGE_SELECT
#define UTE_CHIP_PACKAGE_SELECT             CHIP_5690F
#endif

#if GUI_SCREEN_SIZE_240X284RGB_I330001_SUPPORT
#define TITLE_BAR_HIGH   28    ///标题栏高度
#elif GUI_SCREEN_SIZE_360X360RGB_I332001_SUPPORT
#define TITLE_BAR_HIGH   64    ///标题栏高度
#else
#define TITLE_BAR_HIGH   28
#endif

#if GUI_SCREEN_SIZE_240X284RGB_I330001_SUPPORT
#define TITLE_BAR_HIGH   28    ///标题栏高度
#elif GUI_SCREEN_SIZE_360X360RGB_I332001_SUPPORT
#define TITLE_BAR_HIGH   64    ///标题栏高度
#else
#define TITLE_BAR_HIGH   28
#endif

/*! TP驱动选择，暂时这样使用，后续再封装,wang.luo 2025-01-09 */
#ifndef UTE_DRV_CTP_SELECT
#define UTE_DRV_CTP_SELECT             CTP_CHSC6X
#endif

/*! 默认蓝牙名字 zn.zeng  modify Jul 05, 2021 */
#ifndef DEFAULT_BLE_DEV_NAME
#define DEFAULT_BLE_DEV_NAME "UTE"
#endif
#ifndef UTE_SW_VERSION
#define UTE_SW_VERSION "ABxxxV000001"
#endif
/*!默认公共协议服务开关，默认为关 zn.zeng  modify Jul 06, 2021 */
#ifndef UTE_SERVICE_PUBLIC_BLE_SUPPORT
#define UTE_SERVICE_PUBLIC_BLE_SUPPORT 0
#endif

/*! 中科平台广播UUID,wang.luo 2025-02-13 */
#ifndef UTE_SERVICE_APP_GLORY_ME_SUPPORT
#define UTE_SERVICE_APP_GLORY_ME_SUPPORT 0
#endif

/*! gloryfit 广播数据标识 zn.zeng  modify Jul 05, 2021 */
#if UTE_SERVICE_APP_GLORY_ME_SUPPORT
#define UTE_ADVERTISE_DATA      "\x37\x55"
#else
#define UTE_ADVERTISE_DATA      "\x33\x55"
#endif
/*! 应用端识别是否在搜索界面显示蓝牙名zn.zeng  modify Jul 05, 2021 */
#define UTE_APP_DISPLAY_BT_NAME_ADVERTISE_DATA       "\x22\x22"

/*! 显示蓝牙名蓝牙地址后4位 zn.zeng, 2021-12-08  */
#ifndef UTE_APP_DISPLAY_NAME_ID_SUPPORT
#define UTE_APP_DISPLAY_NAME_ID_SUPPORT 1
#endif

/*! PC工具烧录蓝牙名 wang.luo, 2022-07-14  */
#ifndef UTE_PC_TOOL_WIRTE_BT_NAME_SUPPORT
#define UTE_PC_TOOL_WIRTE_BT_NAME_SUPPORT 1
#endif

#ifndef HAS_BEEN_CONNECTED
#define HAS_BEEN_CONNECTED 0x80
#endif

/** 默认系统支持是最大闹钟数量*/
#ifndef SYSTEM_TIME_ALARMS_MAX_CNT
#define SYSTEM_TIME_ALARMS_MAX_CNT 5
#endif
/** 默认系统时间*/
#ifndef DEFAULT_SYSTEM_TIME_YEAR
#define DEFAULT_SYSTEM_TIME_YEAR 2025
#define DEFAULT_SYSTEM_TIME_MONTH 1
#define DEFAULT_SYSTEM_TIME_DAY 1
#define DEFAULT_SYSTEM_TIME_HOUR 8
#define DEFAULT_SYSTEM_TIME_MIN 0
#define DEFAULT_SYSTEM_TIME_SEC 0
#endif
/*! 默认时间制zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_FORMAT_12HOUR
#define DEFAULT_SYSTEM_TIME_FORMAT_12HOUR false
#define DEFAULT_SYSTEM_TIME_FORMAT_MI false
#endif
/*! 默认时区zn.zeng, 2021-08-18  */
#ifndef DEFAULT_SYSTEM_TIME_ZONE
#define DEFAULT_SYSTEM_TIME_ZONE 8
#endif
/*! 默认个人信息 personalInfo zn.zeng, 2021-08-19  */
#ifndef DEFAULT_PERSONALINFO_AGE
#define DEFAULT_PERSONALINFO_AGE 30
#define DEFAULT_PERSONALINFO_HIGHT 170
#define DEFAULT_PERSONALINFO_WEIGHT 60000 //60kg
#define DEFAULT_PERSONALINFO_ISMAN true
#endif
/** 默认系统最大的每秒函数注册数量*/
#ifndef UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT
#define UTE_MODULE_SYSTEMTEIM_REGISTER_MAX_CNT 24
#endif

/** 系统启动电压*/
#ifndef UTE_DRV_BATTERY_POWER_ON_VOLTAGE
#define UTE_DRV_BATTERY_POWER_ON_VOLTAGE     3300  //mv
#endif

/** 系统自动关机白分比*/
#ifndef UTE_DRV_BATTERY_AUTO_POWER_OFF_LVL
#define UTE_DRV_BATTERY_AUTO_POWER_OFF_LVL    2
#endif

/*电池电量每10秒采样一次，共采样12次，即两分钟更新一次电量百分比*/
#ifndef UTE_DRV_BATTERY_AVG_LEVEL_BUFF_MAX
#define UTE_DRV_BATTERY_AVG_LEVEL_BUFF_MAX    12
#endif

/* 电池容量 zn.zeng 2022-01-07*/
#ifndef UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH
#define UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH      260 //mAh
#endif

/*! 记录电池电量,防止关机再开机电量变多,xjc 2022-01-25*/
#ifndef UTE_MODULE_BATTERY_RECORD_BAT_LVL_SUPPORT
#define UTE_MODULE_BATTERY_RECORD_BAT_LVL_SUPPORT 1
#endif
/*! 充满电后等2分钟才允许掉电,xjc 2022-04-27*/
#ifndef UTE_MODULE_BATTERY_LINEAR_CONSUME_SUPPORT
#define UTE_MODULE_BATTERY_LINEAR_CONSUME_SUPPORT 1
#endif

/*! 使用ute电池百分比计算方式，反之使用原厂百分比计算,wang.luo 2024-11-02 */
#ifndef UTE_DRV_BATTERY_USE_UTE_PERCENTAGE_SUPPORT
#define UTE_DRV_BATTERY_USE_UTE_PERCENTAGE_SUPPORT 1
#endif

/*! 每次恢复出厂设置前保存电量信息,下次开机时恢复当前电量,xjc 2023-02-03*/
#ifndef UTE_MODULE_BATTERY_SAVE_LAST_LVL_BEFORE_FACTORY_SUPPORT
#define UTE_MODULE_BATTERY_SAVE_LAST_LVL_BEFORE_FACTORY_SUPPORT 1
#endif

/*! 电池电量分为几等份，默认5等份，即0 25 50 75 100  xjc, 2021-12-27  */
#ifndef UTE_DRV_BATTERY_TOTAL_INDEX
#define UTE_DRV_BATTERY_TOTAL_INDEX 5
#endif
/*! 低电提醒时电量  xjc, 2021-12-27  */
#ifndef UTE_DRV_BATTERY_LOW_POWER_PERECNT
#define UTE_DRV_BATTERY_LOW_POWER_PERECNT 13
#endif

/*! 电池百分比平滑掉电处理，每次更新百分比只允许掉1%,wang.luo 2025-02-13 */
#ifndef UTE_MODULE_BATTERY_SMOOTH_PERCENTAGE_SUPPORT
#define UTE_MODULE_BATTERY_SMOOTH_PERCENTAGE_SUPPORT 1
#endif

/* 电池曲线 zn.zeng 2022-01-03*/
#ifndef UTE_DRV_BATTERY_000
#define UTE_DRV_BATTERY_000      3579
#define UTE_DRV_BATTERY_010      3691
#define UTE_DRV_BATTERY_020      3741
#define UTE_DRV_BATTERY_030      3781
#define UTE_DRV_BATTERY_040      3815
#define UTE_DRV_BATTERY_050      3858
#define UTE_DRV_BATTERY_060      3922
#define UTE_DRV_BATTERY_070      4023
#define UTE_DRV_BATTERY_080      4119
#define UTE_DRV_BATTERY_090      4221
#define UTE_DRV_BATTERY_100      4335
#endif

/*! 电池最大电压值zn.zeng, 2021-11-09  */
#ifndef UTE_DRV_BATTERY_MAX_VOLTAGE
#if UTE_DRV_BATTERY_100 > 4400
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4450
#elif UTE_DRV_BATTERY_100 > 4350
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4400
#elif UTE_DRV_BATTERY_100 >= 4300
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4350
#else
#define UTE_DRV_BATTERY_MAX_VOLTAGE 4200
#endif
#endif

/*! 充电截止电压：0:4.2v；1:4.35v; 2:4.4v; 3:4.45v,wang.luo 2024-10-30 */
#if UTE_DRV_BATTERY_MAX_VOLTAGE > 4400
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 3
#elif UTE_DRV_BATTERY_MAX_VOLTAGE > 4350
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 2
#elif UTE_DRV_BATTERY_MAX_VOLTAGE > 4300
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 1
#else
#define UTE_DRV_BATTERY_CHARGE_STOP_VOLT 0
#endif

/*! 是否使用代码定义的充电电流,打开这个宏使用代码设置的电流,关闭使用烧录工具设置的电流,wang.luo 2025-03-31 */
#ifndef UTE_DRV_BATTERY_CUSTOM_CHARGE_CURRENT_SUPPORT
#define UTE_DRV_BATTERY_CUSTOM_CHARGE_CURRENT_SUPPORT 1
#endif

/*! 充电电流,默认0.65C,wang.luo 2025-03-31 */
#ifndef UTE_DRV_BATTERY_CHARGE_CURRENT
#define UTE_DRV_BATTERY_CHARGE_CURRENT (UTE_DRV_BATTERY_ELECTRICITY_POWER_MAH * 65 / 100) // 毫安 误差+-5ma
#endif

/*! 默认发送历史数据定时器间隔zn.zeng, 2021-08-23  */
#ifndef UTE_SEND_DATA_TO_PHONE_INVTERVAL
#define UTE_SEND_DATA_TO_PHONE_INVTERVAL 60 // ms
#endif


/*! 使用自定义内存申请,wang.luo 2024-10-21 */
#ifndef UTE_MODULE_USER_MALLOC_SUPPORT
#define UTE_MODULE_USER_MALLOC_SUPPORT 0
#define UTE_MODULE_MEM_POOL_SIZE (1024*5) //内存池大小
#endif

/*! UTE任务配置,wang.luo 2024-11-07 */
#ifndef UTE_TASK_USER_SUPPORT
#define UTE_TASK_USER_SUPPORT 1
#endif
#if UTE_TASK_USER_SUPPORT
#ifndef UTE_TASK_APPLICATION_STACK_SIZE
#define UTE_TASK_APPLICATION_PRIORITY             27
#define UTE_TASK_APPLICATION_STACK_SIZE           (1024 * 4)
#define UTE_TASK_APPLICATION_MESSAGE_MAX_CNT      0x40
#endif
#else
#define UTE_TASK_APPLICATION_STACK_SIZE 0
#endif

/*! 屏宽度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_WIDTH
#define UTE_DRV_SCREEN_WIDTH 240
#endif
/*! 屏高度 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_HEIGHT
#define UTE_DRV_SCREEN_HEIGHT 296
#endif
/*! 0为圆形，1为方形*/
#ifndef UTE_DRV_SCREEN_SHAPE
#define UTE_DRV_SCREEN_SHAPE 1
#endif
/*! 相同分辨率不同R角的在线表盘区分,R角范围0~255 xjc 2023-07-05 */
#ifndef UTE_MODULE_WATCHONLINNE_R_VALUE
#define UTE_MODULE_WATCHONLINNE_R_VALUE   0
#endif
/*! 屏使用16bit色彩 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_SCREEN_PIXEL_BYTES
#define UTE_DRV_SCREEN_PIXEL_BYTES 2
#endif

/*! 默认亮屏时间zn.zeng, 2021-08-20  */
#ifndef DEFAULT_SCREEN_ON_TIME_SECOND
#define DEFAULT_SCREEN_ON_TIME_SECOND 10
#endif

/*! 不同TE模式下的spiclk,用于优化撕裂,spiclk : baud = sys_clk / (div +1),wang.luo 2025-01-11 */
#ifndef UTE_DRV_SCREEN_1TE_SPI_CLK
#define UTE_DRV_SCREEN_1TE_SPI_CLK 27000000 // 27Mhz
#endif
#ifndef UTE_DRV_SCREEN_2TE_SPI_CLK
#define UTE_DRV_SCREEN_2TE_SPI_CLK 12000000 // 12Mhz
#endif

/*! 灭屏后延时清除显示深度，返回时间界面，默认时间 zn.zeng, 2021-11-03  */
#ifndef UTE_MODULE_GUI_CLEAR_DEPTH_AFTER_TIME_SECOND
#define UTE_MODULE_GUI_CLEAR_DEPTH_AFTER_TIME_SECOND 10
#endif

/*! Chsc64x TP升级版本校验功能默认打开，针对chsc64x TP升级版本校验功能，置false则不对比TP项目版本进行强制升级 lkl 2025-1-6  */
#ifndef DEFAULT_TP_UPDATE_VER_CHECKOUT_OPEN
#define DEFAULT_TP_UPDATE_VER_CHECKOUT_OPEN true
#endif

/*! TP固件升级功能开关*/
#ifndef UTE_DRV_TP_COMMON_FW_UPDATE_SUPPORT
#define UTE_DRV_TP_COMMON_FW_UPDATE_SUPPORT 0
#endif

/*! 默认抬手亮屏开关zn.zeng, 2021-08-20  */
#ifndef DEFAULT_HAND_SCREEN_ON_OPEN
#define DEFAULT_HAND_SCREEN_ON_OPEN true
#endif

/*! 勿扰允许抬手亮屏dengli.lu, 2022-08-16  */
#ifndef UTE_NOTDISTURB_ALLOW_HAND_SCREEN_ON_SUPPORT
#define UTE_NOTDISTURB_ALLOW_HAND_SCREEN_ON_SUPPORT 0
#endif

/*! 默认温度单位为摄氏度 zn.zeng, 2021-08-20  */
#ifndef DEFAULT_TEMPERATURE_IS_FAHRENHEIT
#define DEFAULT_TEMPERATURE_IS_FAHRENHEIT false
#endif

/*! 屏最大亮度百分比 dengli.lu, 2021-10-29  */
#ifndef DEFAULT_BACK_LIGHT_PERCENT_MAX
#define DEFAULT_BACK_LIGHT_PERCENT_MAX 100
#endif

/*! 屏最小亮度百分比 dengli.lu, 2021-10-29  */
#ifndef DEFAULT_BACK_LIGHT_PERCENT_MIN
#define DEFAULT_BACK_LIGHT_PERCENT_MIN 25
#endif

/*! 调节屏亮度时增加或者减少的百分比 dengli.lu, 2021-10-29  */
#ifndef BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE
#define BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE 25
#endif

/*! 默认背光百分比zn.zeng, 2021-09-24  */
#ifndef DEFAULT_SCREEN_BACKLIGHT_PERCENT
#define DEFAULT_SCREEN_BACKLIGHT_PERCENT    (BACK_LIGHT_PERCENT_INCREASE_OR_INCREASE*2)
#endif

/*! 默认表盘索引 zn.zeng, 2021-10-25  */
#ifndef DEFAULT_WATCH_INDEX
#define DEFAULT_WATCH_INDEX                      0
#endif

/*! 最大表盘数量，不包括在线表盘 zn.zeng, 2021-10-23  */
#ifndef UTE_MODULE_SCREENS_WATCH_CNT_MAX
#define UTE_MODULE_SCREENS_WATCH_CNT_MAX 5
#endif

/*! 表盘排序地址数组,wang.luo 2024-11-26 */
#ifndef UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS
#define UTE_MODULE_WATCHS_SORT_ADDRESS_ARRAYS {0}
#endif

/*! 默认打开通话模块 zn.zeng, 2021-10-27  */
#ifndef UTE_BT30_CALL_SUPPORT
#define UTE_BT30_CALL_SUPPORT 1
#endif

/*! 是否保存BK的PowerOn状态 xjc, 2022-04-07  */
#ifndef UTE_MODULE_BT_POWER_STATUS_SAVE_SUPPORT
#define UTE_MODULE_BT_POWER_STATUS_SAVE_SUPPORT 1
#endif

/*! 自动关闭bt功能, 2022-06-10  */
#ifndef UTE_BT30_AUTO_POWRER_OFF_SUPPORT
#define UTE_BT30_AUTO_POWRER_OFF_SUPPORT 1
#endif
/*! 自动休眠时间大于UTE_BT30_RETRY_CONNECT_TIME_SECOND, zn.zeng 2022-06-30  */
#ifndef UTE_BT30_AUTO_POWRER_OFF_TIME_SECOND
#define UTE_BT30_AUTO_POWRER_OFF_TIME_SECOND (3*60)
#endif
/*! bt回连,每隔几秒去回连一次 zn.zeng 2022-06-30  */
#ifndef UTE_BT30_RETRY_CONNECT_TIME_INTERVAL
#define UTE_BT30_RETRY_CONNECT_TIME_INTERVAL 10
#endif

#ifndef UTE_MODULE_BT_POWER_DEFAULT_ON
#define UTE_MODULE_BT_POWER_DEFAULT_ON false
#endif

/*! 一次配对连接, casen 2022-02-14*/
#ifndef UTE_MODULE_BT_ONCE_PAIR_CONNECT_SUPPORT
#define UTE_MODULE_BT_ONCE_PAIR_CONNECT_SUPPORT 1
#endif

/*! 每次亮屏之前先清屏，防止闪烁 xjc, 2022-05-18  */
#ifndef UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT
#define UTE_DRV_CLEAR_SCREEN_BEFORE_BACKLIGHT_ON_SUPPORT 0
#endif

// #define UTE_DRV_DSPI_FOR_SCREEN_SUPPORT 1
#ifndef UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT
#define UTE_DRV_SCREEN_TE_SIGNAL_SUPPORT 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_VECTORn PORT_INT1_VECTOR
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PIN IO_PA6
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_PULL 1
#define UTE_DRV_SCREEN_TE_SIGNAL_INT_GPIO_TRIGGER 1
#endif

/*! 屏复位管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_RST_GPIO_PIN
#define UTE_DRV_SCREEN_RST_GPIO_PIN      IO_PA7
#endif
/*! 屏cs管脚zn.zeng, 2021-10-21  */
#ifndef UTE_DRV_SCREEN_CS_GPIO_PIN
#define UTE_DRV_SCREEN_CS_GPIO_PIN      IO_PH6
#endif

#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_SUPPORT 1
#endif
/*! 背光PWM控制输出的频率 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_HZ 200
#endif
/*! 背光PWM控制输出定时器索引 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_PWM_ID
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE6
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5690F)
#define UTE_DRV_SCREEN_BACKLIGHT_PWM_ID GPIO_PE4
#else
#error CHIP ERR
#endif
#endif
/*! 背光控制输出管脚 zn.zeng, 2021-09-24  */
#ifndef UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN   IO_PE6
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN   IO_PE3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5690F)
#define UTE_DRV_SCREEN_BACKLIGHT_GPIO_PIN IO_PE4
#else
#error CHIP ERR
#endif
#endif

/*! 马达PWM控制输出定时器索引 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_ID
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_MOTOR_PWM_ID GPIO_PE3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_MOTOR_PWM_ID GPIO_PF3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5690F)
#define UTE_DRV_MOTOR_PWM_ID GPIO_PE1
#endif
#endif

/*! 控制马达的gpio pin zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_GPIO_PIN
#if (UTE_CHIP_PACKAGE_SELECT == CHIP_5691C_F)
#define UTE_DRV_MOTOR_GPIO_PIN IO_PE3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5691G)
#define UTE_DRV_MOTOR_GPIO_PIN IO_PF3
#elif (UTE_CHIP_PACKAGE_SELECT == CHIP_5690F)
#define UTE_DRV_MOTOR_GPIO_PIN IO_PE1
#else
#error CHIP ERR
#endif
#endif

/*! pwm控制马达支持zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_MODE_SUPPORT
#define UTE_DRV_MOTOR_PWM_MODE_SUPPORT 0
#endif

/*! pwm控制马达的频率zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_MOTOR_PWM_RATE_HZ
#define UTE_DRV_MOTOR_PWM_RATE_HZ 177
#endif

//允许马达振动
#ifndef UTE_MOTOR_ALLOW_VIBRATION_DEFAULT_OPEN
#define UTE_MOTOR_ALLOW_VIBRATION_DEFAULT_OPEN true
#endif

/*! pwm控制马达震动强度 xjc, 2023-05-29  */
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_HIGH
#define UTE_DRV_MOTOR_PWM_VIBRATION_HIGH 90
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_MEDIUM
#define UTE_DRV_MOTOR_PWM_VIBRATION_MEDIUM 70
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_LOW
#define UTE_DRV_MOTOR_PWM_VIBRATION_LOW 50
#endif
#ifndef UTE_DRV_MOTOR_PWM_VIBRATION_NONE
#define UTE_DRV_MOTOR_PWM_VIBRATION_NONE 0
#endif

/*!默认震动强度 level 0-100, dengli.lu, 2022-06-16 */
#ifndef UTE_MODULE_MOTOR_VIBRATION_DEFAULT_LEVEL
#define UTE_MODULE_MOTOR_VIBRATION_DEFAULT_LEVEL UTE_DRV_MOTOR_PWM_VIBRATION_HIGH
#endif

/*!震动时长 unit:ms, lzc, 2022-01-20 */
#ifndef UTE_MOTOR_DURATION_TIME
#define UTE_MOTOR_DURATION_TIME 300
#endif
#ifndef UTE_MOTOR_INTERVAL_TIME
#define UTE_MOTOR_INTERVAL_TIME 600
#endif

#define DRV_TFT_S280X284_I18_ST7789P3_XHL183BA2401_DSPI_SUPPORT 0

/*! 最大title的字节数 zn.zeng, 2021-11-20  */
#ifndef UTE_MUSIC_TITLE_MAX_SIZE
#define UTE_MUSIC_TITLE_MAX_SIZE  52
#endif
/*! 最大歌词的字节数 zn.zeng, 2021-11-20  */
#ifndef UTE_MUSIC_ARTLIST_MAX_SIZE
#define UTE_MUSIC_ARTLIST_MAX_SIZE  103
#endif

/*! 默认语言 zn.zeng, 2021-08-23  */
#ifndef DEFAULT_LANGUAGE
#define DEFAULT_LANGUAGE 0x02//ENGLISH_LANGUAGE_ID
#define SCREEN_TITLE_MULTIPLE_CHINESE_LANGUAGE_SUPPORT              1 //中文 1
#define SCREEN_TITLE_MULTIPLE_ENGLISH_LANGUAGE_SUPPORT              1 //英文 2
#define SCREEN_TITLE_MULTIPLE_KOREAN_LANGUAGE_SUPPORT               0 //韩文 3
#define SCREEN_TITLE_MULTIPLE_JAPANESE_LANGUAGE_SUPPORT             0 //日文 4
#define SCREEN_TITLE_MULTIPLE_GERMAN_LANGUAGE_SUPPORT               0 //德文 5
#define SCREEN_TITLE_MULTIPLE_SPANISH_LANGUAGE_SUPPORT              0 //西班牙文 6
#define SCREEN_TITLE_MULTIPLE_FRENCH_LANGUAGE_SUPPORT               0 //法文 7
#define SCREEN_TITLE_MULTIPLE_ITALIAN_LANGUAGE_SUPPORT              0 //意大利文 8
#define SCREEN_TITLE_MULTIPLE_PORTUGUESE_LANGUAGE_SUPPORT           0 //葡萄牙文 9
#define SCREEN_TITLE_MULTIPLE_ARABIC_LANGUAGE_SUPPORT               0 //阿拉伯文 A
#define SCREEN_TITLE_MULTIPLE_INDIA_LANGUAGE_SUPPORT                0 //India     B
#define SCREEN_TITLE_MULTIPLE_HINDI_LANGUAGE_SUPPORT                0 //印地语  C
#define SCREEN_TITLE_MULTIPLE_POLISH_LANGUAGE_SUPPORT               0 //波兰语  D
#define SCREEN_TITLE_MULTIPLE_RUSSIAN_LANGUAGE_SUPPORT              0 //俄语  E
#define SCREEN_TITLE_MULTIPLE_DUTCH_LANGUAGE_SUPPORT                0 //荷兰语 F
#define SCREEN_TITLE_MULTIPLE_TURKISH_LANGUAGE_SUPPORT              0 //土耳其语  10
#define SCREEN_TITLE_MULTIPLE_BENGALI_LANGUAGE_SUPPORT              0 //孟加拉语  11  Bengali
#define SCREEN_TITLE_MULTIPLE_URDU_LANGUAGE_SUPPORT                 0 //乌尔都语   12  Urdu
#define SCREEN_TITLE_MULTIPLE_INDONESUAN_LANGUAGE_SUPPORT           0 //印度尼西亚语（爪哇语）  13  Indonesian
#define SCREEN_TITLE_MULTIPLE_PUNJABI_LANGUAGE_SUPPORT              0 //旁遮普语  14   Punjabi
#define SCREEN_TITLE_MULTIPLE_THAI_LANGUAGE_SUPPORT                 0 //泰文  15   Thai
#define SCREEN_TITLE_MULTIPLE_CZECH_LANGUAGE_SUPPORT                0 //捷克语  16  Czech
#define SCREEN_TITLE_MULTIPLE_TRADITIONAL_CHINESE_LANGUAGE_SUPPORT  0 //繁体中文
#define SCREEN_TITLE_MULTIPLE_ROMANIAN_LANGUAGE_SUPPORT             0 //罗马尼亚语 limba 0x1B
#define SCREEN_TITLE_MULTIPLE_VIETNAMESE_LANGUAGE_SUPPORT           0 //越南语 0x63
#endif
/*! UTE多国语言,wang.luo 2024-11-08 */
#ifndef UTE_MULTIPLE_LANGUAGE_SUPPORT
#define UTE_MULTIPLE_LANGUAGE_SUPPORT 1
#endif

#ifndef UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT
#define UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT 1
#define ALARM_REPEAT_REMIND_DEFAULT_OPEN true//默认重复提醒开关
#define ALARM_REPEAT_REMIND_DEFAULT_TIME_MIN 10
#define ALARM_REPEAT_REMIND_DEFAULT_TIMES 3//默认重复提醒次数，未手动关闭时重复提醒5次后不再提醒
#endif // UTE_MODULE_LOCAL_ALARM_REPEAT_REMIND_SUPPORT

/*! 本地闹钟默认振动次数 dengli.lu, 2022-08-10  */
#ifndef UTE_LOCAL_ALARM_DEFAULT_MOTOR_TIMES
#define UTE_LOCAL_ALARM_DEFAULT_MOTOR_TIMES 10
#endif

#ifndef UTE_LOCAL_ALARM_DEFAULT_RING_TIMES
#define UTE_LOCAL_ALARM_DEFAULT_RING_TIMES  20                  //闹钟默认响铃时间 20S
#endif // UTE_LOCAL_ALARM_DEFAULT_RING_TIMES

/*! 本地闹钟dengli.lu, 2021-11-25  */
#ifndef UTE_MODULE_LOCAL_ALARM_SUPPORT
#define UTE_MODULE_LOCAL_ALARM_SUPPORT 1
#endif

#ifndef UTE_NOTIFY_MSG_CONTENT_MAX_SIZE
#define UTE_NOTIFY_MSG_CONTENT_MAX_SIZE 240
#endif
/*! 消息推送保存的最大条数zn.zeng, 2021-08-25  */
#ifndef UTE_MODULE_NOTIFY_SAVE_CNT
#define UTE_MODULE_NOTIFY_SAVE_CNT 8
#endif

/*! 消息推送马达震动在消息提醒界面手动开启，防止中科平台休眠时震动时长不固定,wang.luo 2025-01-16 */
#ifndef UTE_MODULE_NOTIFY_START_MOTOR_INTO_SCREEN_SUPPORT
#define UTE_MODULE_NOTIFY_START_MOTOR_INTO_SCREEN_SUPPORT 1
#endif

/* 支持应用通知选择显示功能 必须支持的三样 xjc, 2022-01-08 */
#define SOCIAL_APP_MMS_SUPPORT     1
#define SOCIAL_APP_CALL_SUPPORT    1
#define SOCIAL_APP_OTHER_SUPPORT   1
#ifndef SOCIAL_APP_QQ_SUPPORT
#define SOCIAL_APP_QQ_SUPPORT   1
#endif
#ifndef SOCIAL_APP_WECHAT_SUPPORT
#define SOCIAL_APP_WECHAT_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FACEBOOK_SUPPORT
#define SOCIAL_APP_FACEBOOK_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TWITTER_SUPPORT
#define SOCIAL_APP_TWITTER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_WHATSAPP_SUPPORT
#define SOCIAL_APP_WHATSAPP_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FACEBOOK_MESSENGER_SUPPORT
#define SOCIAL_APP_FACEBOOK_MESSENGER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_LINE_SUPPORT
#define SOCIAL_APP_LINE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_SKYPE_SUPPORT
#define SOCIAL_APP_SKYPE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_HANGOUTS_SUPPORT
#define SOCIAL_APP_HANGOUTS_SUPPORT   1
#endif
#ifndef SOCIAL_APP_LINKED_IN_SUPPORT
#define SOCIAL_APP_LINKED_IN_SUPPORT   1
#endif
#ifndef SOCIAL_APP_INSTAGRAM_SUPPORT
#define SOCIAL_APP_INSTAGRAM_SUPPORT   1
#endif
#ifndef SOCIAL_APP_VIBER_SUPPORT
#define SOCIAL_APP_VIBER_SUPPORT   1
#endif
#ifndef SOCIAL_APP_KAKAO_TALK_SUPPORT
#define SOCIAL_APP_KAKAO_TALK_SUPPORT   1
#endif
#ifndef SOCIAL_APP_VKONTAKTE_SUPPORT
#define SOCIAL_APP_VKONTAKTE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_SNAPCHAT_SUPPORT
#define SOCIAL_APP_SNAPCHAT_SUPPORT   1
#endif
#ifndef SOCIAL_APP_GOOGLE_PLUS_SUPPORT
#define SOCIAL_APP_GOOGLE_PLUS_SUPPORT   1
#endif
#ifndef SOCIAL_APP_GMAIL_SUPPORT
#define SOCIAL_APP_GMAIL_SUPPORT   1
#endif
#ifndef SOCIAL_APP_FLICKR_SUPPORT
#define SOCIAL_APP_FLICKR_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TUMBLR_SUPPORT
#define SOCIAL_APP_TUMBLR_SUPPORT   1
#endif
#ifndef SOCIAL_APP_PINTEREST_SUPPORT
#define SOCIAL_APP_PINTEREST_SUPPORT   1
#endif
#ifndef SOCIAL_APP_YOUTUBE_SUPPORT
#define SOCIAL_APP_YOUTUBE_SUPPORT   1
#endif
#ifndef SOCIAL_APP_TELEGRAM_SUPPORT
#define SOCIAL_APP_TELEGRAM_SUPPORT   1
#endif
#ifndef SOCIAL_APP_PAYTM_SUPPORT
#define SOCIAL_APP_PAYTM_SUPPORT    0
#endif
#ifndef SOCIAL_APP_ZALO_SUPPORT
#define SOCIAL_APP_ZALO_SUPPORT 0
#endif
#ifndef SOCIAL_APP_IMO_SUPPORT
#define SOCIAL_APP_IMO_SUPPORT  0
#endif
#ifndef SOCIAL_APP_TRUECALLER_SUPPORT
#define SOCIAL_APP_TRUECALLER_SUPPORT   0
#endif
#ifndef SOCIAL_APP_MICROSOFT_TEAMS_SUPPORT
#define SOCIAL_APP_MICROSOFT_TEAMS_SUPPORT  0
#endif

#if APP_DYNAMIC_ADDITIONAL_SOCIAL_APP_SUPPORT

#ifndef SOCIAL_APP_OUTLOOK_SUPPORT
#define SOCIAL_APP_OUTLOOK_SUPPORT  0
#endif
#ifndef SOCIAL_APP_SWIGGY_SUPPORT
#define SOCIAL_APP_SWIGGY_SUPPORT   0
#endif
#ifndef SOCIAL_APP_ZOMATO_SUPPORT
#define SOCIAL_APP_ZOMATO_SUPPORT   0
#endif
#ifndef SOCIAL_APP_GPAY_SUPPORT
#define SOCIAL_APP_GPAY_SUPPORT 0
#endif
#ifndef SOCIAL_APP_PHONEPE_SUPPORT
#define SOCIAL_APP_PHONEPE_SUPPORT  0
#endif
#ifndef SOCIAL_APP_HOTSTAR_SUPPORT
#define SOCIAL_APP_HOTSTAR_SUPPORT  0
#endif
#ifndef SOCIAL_APP_PRIMEVIDEO_SUPPORT
#define SOCIAL_APP_PRIMEVIDEO_SUPPORT   0
#endif
#ifndef SOCIAL_APP_FLIPKART_SUPPORT
#define SOCIAL_APP_FLIPKART_SUPPORT 0
#endif
#ifndef SOCIAL_APP_AMAZON_SUPPORT
#define SOCIAL_APP_AMAZON_SUPPORT   0
#endif
#ifndef SOCIAL_APP_MYNTRA_SUPPORT
#define SOCIAL_APP_MYNTRA_SUPPORT   0
#endif
#ifndef SOCIAL_APP_NOISEAPP_SUPPORT
#define SOCIAL_APP_NOISEAPP_SUPPORT 0
#endif
#ifndef SOCIAL_APP_DAILYHUNT_SUPPORT
#define SOCIAL_APP_DAILYHUNT_SUPPORT    0
#endif
#ifndef SOCIAL_APP_INSHORTS_SUPPORT
#define SOCIAL_APP_INSHORTS_SUPPORT 0
#endif

#ifndef SOCIAL_APP_BOOKMYSHOW_SUPPORT
#define SOCIAL_APP_BOOKMYSHOW_SUPPORT   0
#endif

#ifndef SOCIAL_APP_CALENDAR_SUPPORT
#define SOCIAL_APP_CALENDAR_SUPPORT 0
#endif

#ifndef SOCIAL_APP_JIOTV_SUPPORT
#define SOCIAL_APP_JIOTV_SUPPORT    0
#endif

#ifndef SOCIAL_APP_MAKEMYTRIP_SUPPORT
#define SOCIAL_APP_MAKEMYTRIP_SUPPORT   0
#endif

#ifndef SOCIAL_APP_NETFLIX_SUPPORT
#define SOCIAL_APP_NETFLIX_SUPPORT  0
#endif

#ifndef SOCIAL_APP_OLA_SUPPORT
#define SOCIAL_APP_OLA_SUPPORT  0
#endif

#ifndef SOCIAL_APP_REFLEXAPP_SUPPORT
#define SOCIAL_APP_REFLEXAPP_SUPPORT    0
#endif

#ifndef SOCIAL_APP_UBER_SUPPORT
#define SOCIAL_APP_UBER_SUPPORT 0
#endif

#ifndef SOCIAL_APP_YTMUSIC_SUPPORT
#define SOCIAL_APP_YTMUSIC_SUPPORT  0
#endif

//add 2022-11-22
#ifndef SOCIAL_APP_WHATSAPP_BUSINESS_SUPPORT
#define SOCIAL_APP_WHATSAPP_BUSINESS_SUPPORT  0
#endif

#ifndef SOCIAL_APP_DUNZO_SUPPORT
#define SOCIAL_APP_DUNZO_SUPPORT    0
#endif

#ifndef SOCIAL_APP_GAANA_SUPPORT
#define SOCIAL_APP_GAANA_SUPPORT 0
#endif

#ifndef SOCIAL_APP_GOOGLE_DRIVE_SUPPORT
#define SOCIAL_APP_GOOGLE_DRIVE_SUPPORT  0
#endif

#ifndef SOCIAL_APP_GOOGLECHAT_SUPPORT
#define SOCIAL_APP_GOOGLECHAT_SUPPORT 0
#endif

#ifndef SOCIAL_APP_WYNKMUSIC_SUPPORT
#define SOCIAL_APP_WYNKMUSIC_SUPPORT  0
#endif

#ifndef SOCIAL_APP_YAHOO_SUPPORT
#define SOCIAL_APP_YAHOO_SUPPORT  0
#endif

#ifndef SOCIAL_APP_TITANSMARTWORLD_SUPPORT
#define SOCIAL_APP_TITANSMARTWORLD_SUPPORT    0
#endif

#ifndef SOCIAL_APP_SLACK_SUPPORT
#define SOCIAL_APP_SLACK_SUPPORT 0
#endif

#ifndef SOCIAL_APP_SPOTIFY_SUPPORT
#define SOCIAL_APP_SPOTIFY_SUPPORT  0
#endif
#endif

/*! 本地勿扰模式设置,casen 2022-08-26  */
#ifndef UTE_MODULE_LOCAL_SET_NOT_DISTURB_SUPPORT
#define UTE_MODULE_LOCAL_SET_NOT_DISTURB_SUPPORT            1
#endif
/*! 勿扰默认关闭 zn.zeng, 2021-10-22  */
#ifndef DEFAULT_DONOT_DISTURB_OPNE
#define DEFAULT_DONOT_DISTURB_OPNE false
#endif
#ifndef DEFAULT_DONOT_DISTURB_REJECT_CALL_OPNE
#define DEFAULT_DONOT_DISTURB_REJECT_CALL_OPNE false
#endif
#ifndef DEFAULT_DONOT_DISTURB_START_HOUR_MIN_VALUE
#define DEFAULT_DONOT_DISTURB_START_HOUR_MIN_VALUE  0x01 //00:01
#endif
#ifndef DEFAULT_DONOT_DISTURB_END_HOUR_MIN_VALUE
#define DEFAULT_DONOT_DISTURB_END_HOUR_MIN_VALUE  0x59f  //23:59
#endif

/*! 天气增加紫外强度和湿度 2022-09-22  */
#ifndef UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT
#define UTE_MODULE_WEATHER_HUMIDITY_ULTRAVIOLET_SUPPORT 0
#endif

/* 天气城市名支持,utf8编码 txj 2022-11-10*/
#ifndef UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT
#define UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT 1
#endif
#if UTE_MODULE_WEATHER_CITY_NAME_NEW_SUPPORT
/* 天气城市名支持最大字节大小 txj 2022-11-10 */
#ifndef UTE_WEATHER_CITY_NAME_TITLE_MAX_SIZE
#define UTE_WEATHER_CITY_NAME_TITLE_MAX_SIZE 100
#endif
#endif

#ifndef UTE_MODULE_SPORT_SUPPORT
#define UTE_MODULE_SPORT_SUPPORT 0
#endif

#ifndef UTE_MODULE_HEART_SUPPORT
#define UTE_MODULE_HEART_SUPPORT 0
#endif
/*! 默认心率报警是否打开 zn.zeng, 2021-08-20  */
#ifndef DEFAULT_HEARTWARNING_IS_OPEN
#define DEFAULT_HEARTWARNING_IS_OPEN false
#define DEFAULT_HEARTWARNING_MIN_VALUE 40
#define DEFAULT_HEARTWARNING_MAX_VALUE 100
#endif
/*! 默认运动心率报警是否打开 dengli.lu, 2022-08-03  */
#ifndef DEFAULT_SPORT_MAX_HEARTWARNING_IS_OPEN
#define DEFAULT_SPORT_MAX_HEARTWARNING_IS_OPEN false
#define DEFAULT_SPORT_MIN_HEARTWARNING_IS_OPEN false
#define DEFAULT_SPORT_HEARTWARNING_MIN_VALUE 40
#define DEFAULT_SPORT_HEARTWARNING_MAX_VALUE 100
#endif
/*! 默认24小时自动心率打开 zn.zeng, 2021-08-30  */
#ifndef DEFAULT_HEART24AUTO_TEST_IS_OPEN
#define DEFAULT_HEART24AUTO_TEST_IS_OPEN true
#endif
/*! 心率警告功能 zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_VALUE_SUPPORT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_VALUE_SUPPORT 0
#endif
/*! 心率警告第一次提醒时间zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_FRIST_SECOND_CNT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_FRIST_SECOND_CNT 60
#endif
/*! 心率警告重复提醒时间zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_HEART_MIN_MAX_WARNING_RELOAD_SECOND_CNT
#define UTE_MODULE_HEART_MIN_MAX_WARNING_RELOAD_SECOND_CNT 300
#endif
/*! 心率数据保存最大天数zn.zeng, 2021-08-30  */
#ifndef UTE_MODULE_HEART_SAVE_DATA_MAX_DAYS
#define UTE_MODULE_HEART_SAVE_DATA_MAX_DAYS 7
#endif
/*! 心率最大最小值数字显示跟随柱状图中的最大最小值 xjc, 2022-01-17  */
#ifndef UTE_HEART_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT
#define UTE_HEART_MAX_MIN_AVG_FOLLOW_HISTOGRAM_SUPPORT 0
#endif

/*! 血氧功能zn.zeng, 2021-07-23  */
#ifndef UTE_MODULE_BLOODOXYGEN_SUPPORT
#define UTE_MODULE_BLOODOXYGEN_SUPPORT 0
#endif
/*! vcxx系列血氧功能 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_BLOODOXYGEN_VCXX_SUPPORT
#define UTE_DRV_BLOODOXYGEN_VCXX_SUPPORT 0
#endif
/*! 血氧测试超时时间 zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_BLOODOXYGEN_TEST_TIMEOUT_SECOND
#define UTE_MODULE_BLOODOXYGEN_TEST_TIMEOUT_SECOND 65
#endif
/*! 血氧测试默认时间时间 zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_BLOODOXYGEN_TEST_DEFAULT_SECOND
#define UTE_MODULE_BLOODOXYGEN_TEST_DEFAULT_SECOND 40
#endif
/*!血氧自动测试模式默认打开 zn.zeng, 2021-08-31  */
#ifndef UTE_MODULE_BLOODOXYGEN_IS_AUTO_OPEN
#define UTE_MODULE_BLOODOXYGEN_IS_AUTO_OPEN false
#endif
/*!血氧时间段测试模式默认关闭 zn.zeng, 2021-08-31  */
#ifndef UTE_MODULE_BLOODOXYGEN_IS_AUTO_TIME_BUCKET_OPEN
#define UTE_MODULE_BLOODOXYGEN_IS_AUTO_TIME_BUCKET_OPEN false
#endif
/*!血氧自动测试时间间隔，单位为分钟，默认为10分钟     zn.zeng, 2021-08-31  */
#ifndef UTE_MODULE_BLOODOXYGEN_AUTO_INTERVAL_MIN
#define UTE_MODULE_BLOODOXYGEN_AUTO_INTERVAL_MIN 10
#endif
/*! 血氧测试时间段zn.zeng, 2021-08-31  */
#ifndef UTE_MODULE_BLOODOXYGEN_TIME_BUCKET_START
#define UTE_MODULE_BLOODOXYGEN_TIME_BUCKET_START 0X0001
#define UTE_MODULE_BLOODOXYGEN_TIME_BUCKET_END 0X173B
#endif
/*! zn.zeng, 2021-08-31  */
#ifndef UTE_MODULE_BLOODOXYGEN_SAVE_DATA_MAX_DAYS
#define UTE_MODULE_BLOODOXYGEN_SAVE_DATA_MAX_DAYS 7
#endif

//二维码链接内容
#ifndef UTE_BINDING_QRENCODE_LINK
#define UTE_BINDING_QRENCODE_LINK "https://app.uteasy.com/gloryme/download/index.html"
#endif

/*! gsensro默认acc采样范围 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_GSENSOR_DEFAULT_ACC_RANGE_VALUE
#define UTE_DRV_GSENSOR_DEFAULT_ACC_RANGE_VALUE 4
#endif
/*! gsensro默认采样频率 zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_GSENSOR_DEFAULT_ACC_RATE_VALUE
#define UTE_DRV_GSENSOR_DEFAULT_ACC_RATE_VALUE 1 //0:20HZ 1:40HZ 2:100HZ, 详情查看 enum ute_drv_gsensor_acc_rate_t
#endif

/*! 抬手亮屏参数 zn.zeng, 2021-10-22  */
#ifndef ROLLOVER_HAND_SCREEN_X_MIN
#define ROLLOVER_HAND_SCREEN_X_MIN  -46
#define ROLLOVER_HAND_SCREEN_X_MAX  46
#define ROLLOVER_HAND_SCREEN_Y_MIN  -140
#define ROLLOVER_HAND_SCREEN_Y_MAX  40
#define ROLLOVER_HAND_SCREEN_Z_MIN  -136
#define ROLLOVER_HAND_SCREEN_Z_MAX  128
#define ROLLOVER_HAND_SCREEN_ACC_DIFF_VALUE  40
#endif

/*! 计步数据最大保存天数zn.zeng, 2021-08-24  */
#ifndef UTE_MODULE_SPORT_SAVE_STEP_DATA_MAX_DAYS
#define UTE_MODULE_SPORT_SAVE_STEP_DATA_MAX_DAYS 7
#endif
/*! 睡眠数据最大保存天数zn.zeng, 2021-10-26  */
#ifndef UTE_MODULE_SLEEP_DATA_MAX_DAYS
#define UTE_MODULE_SLEEP_DATA_MAX_DAYS 7
#endif
/*! 快速眼动,wang.luo 2024-11-13 */
#ifndef UTE_REM_SLEEP_SUPPORT
#define UTE_REM_SLEEP_SUPPORT 1
#endif
/* 睡眠数据采样支持 zn.zeng 2021-12-29*/
#ifndef UTE_MODULE_SLEEP_SAMPLE_DATA_SUPPORT
#define UTE_MODULE_SLEEP_SAMPLE_DATA_SUPPORT 0
#endif
/*gesnsor 采集原始数据*/
#ifndef APP_DBG_GSENSOR_DATA
#define APP_DBG_GSENSOR_DATA 0
#endif
/* 多运动步数数据累加到状态界面 xjc, 2022-01-08 */
#ifndef UTE_MODULE_SPORT_TODAY_ADD_ALL_SPORT_DATA_SUPPORT
#define UTE_MODULE_SPORT_TODAY_ADD_ALL_SPORT_DATA_SUPPORT 1
#endif
/* 多运动kcal数数据累加到状态界面 dengli.lu, 2022-08-28 */
#ifndef UTE_MODULE_SPORT_TODAY_ADD_KCAL_SPORT_DATA_SUPPORT
#define UTE_MODULE_SPORT_TODAY_ADD_KCAL_SPORT_DATA_SUPPORT 0
#endif
#ifndef DEFAULT_DONOT_DISTURB_END_TIME
#define DEFAULT_DONOT_DISTURB_END_TIME  0x1700   //23:00
#endif
/*! 久坐提醒午休可设置时间，默认关闭 dengli.lu, 2022-08-16  */
#ifndef UTE_MODULE_SEDENTARY_NOTIFY_SET_NOONSLEEP_TIME
#define UTE_MODULE_SEDENTARY_NOTIFY_SET_NOONSLEEP_TIME 0
#endif
/*! 久坐提醒默认关闭 dengli.lu, 2022-08-16  */
#ifndef DEFAULT_SEDENTARY_NOTIFY_OPNE
#define DEFAULT_SEDENTARY_NOTIFY_OPNE false
#endif
#ifndef DEFAULT_SEDENTARY_NOTIFY_TIME_INTERVAL
#define DEFAULT_SEDENTARY_NOTIFY_TIME_INTERVAL 0x3c//60分钟
#endif
#ifndef DEFAULT_SEDENTARY_NOTIFY_START_TIME
#define DEFAULT_SEDENTARY_NOTIFY_START_TIME  0x0800 //08:00
#endif
#ifndef DEFAULT_SEDENTARY_NOTIFY_END_TIME
#define DEFAULT_SEDENTARY_NOTIFY_END_TIME  0x1700   //23:00
#endif
/*! 午休勿打扰 黄鹤, 2022-03-30  */
#ifndef DEFAULT_NOON_SLEEP_OPNE
#define DEFAULT_NOON_SLEEP_OPNE true
#endif
#ifndef DEFAULT_NOON_SLEEP_START_TIME
#define DEFAULT_NOON_SLEEP_START_TIME  0x0c00 //12:00
#endif
#ifndef DEFAULT_NOON_SLEEP_END_TIME
#define DEFAULT_NOON_SLEEP_END_TIME  0x0e00   //14:00
#endif
/*! 站立时长保存数据最大天数,casen 2022-07-14  */
#ifndef UTE_MODULE_SPORT_STANDTIME_SAVE_DATA_MAX_DAYS
#define UTE_MODULE_SPORT_STANDTIME_SAVE_DATA_MAX_DAYS 7
#endif
/*! 默认目标步数值 zn.zeng, 2021-08-20  */
#ifndef DEFAULT_STEP_TARGET_CNT
#define DEFAULT_STEP_TARGET_CNT 10000
#endif
#ifndef DEFAULT_STEP_TARGET_OPEN
#define DEFAULT_STEP_TARGET_OPEN true
#endif
#ifndef DEFAULT_KCAL_TARGET_CNT
#define DEFAULT_KCAL_TARGET_CNT 500
#endif
#ifndef DEFAULT_KCAL_TARGET_OPEN
#define DEFAULT_KCAL_TARGET_OPEN true
#endif
#ifndef DEFAULT_DISTANCE_TARGET_CNT
#define DEFAULT_DISTANCE_TARGET_CNT 5000
#endif
#ifndef DEFAULT_DISTANCE_TARGET_OPEN
#define DEFAULT_DISTANCE_TARGET_OPEN true
#endif
#ifndef DEFAULT_STAND_TIME_TARGET_CNT
#define DEFAULT_STAND_TIME_TARGET_CNT 60
#endif
#ifndef DEFAULT_STAND_TIME_TARGET_OPEN
#define DEFAULT_STAND_TIME_TARGET_OPEN true
#endif
#ifndef DEFAULT_SPORT_TIME_TARGET_CNT
#define DEFAULT_SPORT_TIME_TARGET_CNT 60
#endif
#ifndef DEFAULT_SPORE_TIME_TARGET_OPEN
#define DEFAULT_SPORE_TIME_TARGET_OPEN true
#endif
/*! 抬腕亮屏默认打开 raymond, 2022-03-03  */
#ifndef DEFAULT_LIFT_WRIST_OPNE
#define DEFAULT_LIFT_WRIST_OPNE true
#endif
#ifndef DEFAULT_LIFT_WRIST_SCHEDULED_OPNE
#define DEFAULT_LIFT_WRIST_SCHEDULED_OPNE false
#endif
#ifndef DEFAULT_LIFT_WRIST_START_HOUR_MIN_VALUE
#define DEFAULT_LIFT_WRIST_START_HOUR_MIN_VALUE 0x0800 //08:00
#endif
#ifndef DEFAULT_LIFT_WRIST_END_HOUR_MIN_VALUE
#define DEFAULT_LIFT_WRIST_END_HOUR_MIN_VALUE 0x1600 //22:00
#endif

/*! 仅主界面允许落腕息屏，其他不允许，默认开启，dengli.lu 2022-08-31 */
#ifndef UTE_MODULE_HAND_SCREEN_OFF_ONLY_WATCHMAIN_ID_SUPPORT
#define UTE_MODULE_HAND_SCREEN_OFF_ONLY_WATCHMAIN_ID_SUPPORT 1
#endif

/*! 多运动倒计时数字时间zn.zeng, 2021-11-11  */
#ifndef UTE_MODULE_SPROT_MORE_SPORT_COUNT_ZORE
#define UTE_MODULE_SPROT_MORE_SPORT_COUNT_ZORE 3
#endif

/*! 多运动最小保存数据时间，秒单位 zn.zeng, 2021-11-11  */
#ifndef UTE_MODULE_SPORT_MORE_SPORT_MIN_SAVE_TIME
#define UTE_MODULE_SPORT_MORE_SPORT_MIN_SAVE_TIME 60
#endif
/*! 多运动默认有跳绳游泳次数 xjc, 2022-09-27  */
#ifndef UTE_MODULE_SPORT_WITH_TIMES_SUPPORT
#define UTE_MODULE_SPORT_WITH_TIMES_SUPPORT 1
#endif

/*! 多运动最大保存次数zn.zeng, 2021-11-12  */
#ifndef UTE_MODULE_SPORT_MORE_SPORTS_DATA_MAX_CNT
#define UTE_MODULE_SPORT_MORE_SPORTS_DATA_MAX_CNT 40
#endif

/*! 多运动支持百种运动标志, xjc 2022-03-29
注意：打开该宏需要将所有运动的宏添加到对应的项目中，具体可参考RB303项目配置
1、开启多运动支持百种运动标志后,运动列表等那些有运动排列的数组，运动排序需要保持与sport_mode_type中顺序一致,详情可参考trainingList中I202001的处理;
2、本项目支持多少种运动,UTE_MODULE_SPORT_MAX_SPORT_NUM就填多少，同时运动宏开启对应的数量;
3、运动显示开关宏,需要默认显示的置1,不要默认显示置0;
4、默认运动的显示顺序,开了几个运动就按需要的顺序填写,不要重复,不显示的置0;
*/
#ifndef UTE_MODULE_SPORT_HUNDRED_SUPPORT
#define UTE_MODULE_SPORT_HUNDRED_SUPPORT 0
#endif
/*! 支持的运动数量, xjc 2022-03-09  */
#ifndef UTE_MODULE_SPORT_MAX_SPORT_NUM
#define UTE_MODULE_SPORT_MAX_SPORT_NUM 25
#endif
/*! 多运动界面显示的最少运动数量, xjc 2022-03-29 */
#ifndef UTE_MODULE_SPORT_DISPLAY_MIN_SPORT_NUM
#define UTE_MODULE_SPORT_DISPLAY_MIN_SPORT_NUM 1
#endif
/*! 多运动界面显示的最大运动数量, xjc 2022-03-29 */
#ifndef UTE_MODULE_SPORT_DISPLAY_MAX_SPORT_NUM
#define UTE_MODULE_SPORT_DISPLAY_MAX_SPORT_NUM (UTE_MODULE_SPORT_MAX_SPORT_NUM)
#endif

/*! UTE运动计步算法,wang.luo 2024-11-04 */
#ifndef UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_SUPPORT
#define UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_SUPPORT 1
#endif

/*! 省略运动算法定时器,把运动算法丢到系统500ms定时器中,wang.luo 2025-02-21 */
#ifndef UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_ELLIPSIS_TIMER_SUPPORT
#define UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_ELLIPSIS_TIMER_SUPPORT 0
#endif

/*! 运动算法定时器时长,wang.luo 2024-11-12 */
#ifndef UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_TIMER_DURATION
#define UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_TIMER_DURATION 600
#endif // !UTE_MODULE_ALL_SPORT_STEP_ALGORITHMS_TIMER_

/*! 运动计步算法自动切换主频以降低功耗,静止时降低主频,运动时提高主频,wang.luo 2025-02-21 */
#ifndef UTE_MODULE_SPROT_ALGO_AUTO_SWITCH_SYSCLK_SUPPORT
#define UTE_MODULE_SPROT_ALGO_AUTO_SWITCH_SYSCLK_SUPPORT 1
#endif

/*! 打开拍照界面app也打开,dengli.lu 2022-08-18*/
#ifndef UTE_MODULE_SPORT_TAKE_PICTURE_OPEN_APP_SCREEN
#define UTE_MODULE_SPORT_TAKE_PICTURE_OPEN_APP_SCREEN 1
#endif

/*! 快捷开关支持zn.zeng, 2021-08-24  */
#ifndef QUICK_SWITCH_FINDBAND_SUPPORT
#define QUICK_SWITCH_FINDBAND_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_TURNTHEWRIST_SUPPORT
#define QUICK_SWITCH_TURNTHEWRIST_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_SEDENTARY_SUPPORT
#define QUICK_SWITCH_SEDENTARY_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_NOT_DISTURB_SUPPORT
#define QUICK_SWITCH_NOT_DISTURB_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_ANTILOST_SUPPORT
#define QUICK_SWITCH_ANTILOST_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_REJECT_CALL_SUPPORT
#define QUICK_SWITCH_REJECT_CALL_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_24H_HEART_SUPPORT
#define QUICK_SWITCH_24H_HEART_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_DISPLAY_TIME_SUPPORT
#define QUICK_SWITCH_DISPLAY_TIME_SUPPORT 0
#endif
#ifndef QUICK_SWITCH_SHOCK_TIME_SUPPORT
#define QUICK_SWITCH_SHOCK_TIME_SUPPORT 0
#endif
//快捷开关：本地勿扰设置时间
#ifndef QUICK_SWITCH_LOCAL_WURAO_SET_TIME_SUPPORT
#define QUICK_SWITCH_LOCAL_WURAO_SET_TIME_SUPPORT 0
#endif
//快捷开关：本地24小时制
#ifndef QUICK_SWITCH_LOCAL_IS24HOUR_SUPPORT
#define QUICK_SWITCH_LOCAL_IS24HOUR_SUPPORT 0
#endif

/*! vcxx 数据采样，默认关闭 zn.zeng, 2021-07-13  */
#ifndef DUG_VCXX_HEART_SUPPORT
#define DUG_VCXX_HEART_SUPPORT 0
#endif
/*! vcxx 数据采样，默认关闭 zn.zeng, 2021-07-13  */
#ifndef DUG_VCXX_BLOOD_OXYGEN_SUPPORT
#define DUG_VCXX_BLOOD_OXYGEN_SUPPORT 0
#endif
/*! 心率算法，x,y轴互换zn.zeng, 2021-10-22  */
#ifndef UTE_DRV_HEART_VCXX_ARM_XY_EXCHANGE
#define UTE_DRV_HEART_VCXX_ARM_XY_EXCHANGE 1
#endif

/*! vcxx 保持心率电源，不测量时使用wear模式,wang.luo 2024-11-22 */
#ifndef UTE_DRV_HEART_VCXX_REMAIN_POWER_SUPPORT
#define UTE_DRV_HEART_VCXX_REMAIN_POWER_SUPPORT 0
#endif

/*! 夜间开启佩戴检测优化睡眠监测,wang.luo 2025-01-10 */
#ifndef UTE_DRV_HEART_VCXX_NIGHT_OPTIMIZE_SLEEP_SUPPORT
#define UTE_DRV_HEART_VCXX_NIGHT_OPTIMIZE_SLEEP_SUPPORT 0
#endif

#define DRV_HEART_VCXX_LIGHT_I_MIN_VALUE 100
#define DRV_HEART_VCXX_LIGHT_I_MAX_VALUE 120
#define DRV_HEART_VCXX_LIGHT_LEAKGE_DIFF_VALUE 32
#define DRV_HEART_VCXX_PS_MIN_VALUE 210
#define DRV_HEART_VCXX_BIO_PASS_VALUE 60

/*! 一级界面默认排序,wang.luo 2024-11-16 */
#ifndef UTE_CUI_SCREEN_TBL_SORT_CNT_DEFAULT
#define UTE_CUI_SCREEN_TBL_SORT_CNT_DEFAULT 7
#define UTE_CUI_SCREEN_TBL_SORT_ARRAY_DEFAULT {FUNC_CLOCK, FUNC_ACTIVITY, FUNC_HEARTRATE, FUNC_SLEEP, FUNC_BLOOD_OXYGEN, FUNC_BT, FUNC_COMPO_SELECT}
#endif

/*! 体温模块支持zn.zeng, 2021-12-01  */
#ifndef UTE_MODULE_TEMPERATURE_SUPPORT
#define UTE_MODULE_TEMPERATURE_SUPPORT     0
#endif

/* 充电CE认证 zn.zeng 2022-01-03*/
#ifndef UTE_DRV_BATTERY_CE_AUTH_SUPPORT
#define UTE_DRV_BATTERY_CE_AUTH_SUPPORT 1
#endif
/* 充电CE认证允许充电温度 zn.zeng 2022-01-03*/
#ifndef UTE_DRV_BATTERY_CE_AUTH_ALLOW_TEMPERATURE
#define UTE_DRV_BATTERY_CE_AUTH_ALLOW_TEMPERATURE 42.0f
#endif
#ifndef UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_TEMPERATURE
#define UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_TEMPERATURE 45.0f
#endif
#ifndef UTE_DRV_BATTERY_CE_AUTH_ALLOW_LOW_TEMPERATURE
#define UTE_DRV_BATTERY_CE_AUTH_ALLOW_LOW_TEMPERATURE 3.0f
#endif
#ifndef UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_LOW_TEMPERATURE
#define UTE_DRV_BATTERY_CE_AUTH_NOT_ALLOW_LOW_TEMPERATURE 0.0f
#endif

#if (UTE_MODULE_TEMPERATURE_SUPPORT || UTE_DRV_BATTERY_CE_AUTH_SUPPORT)
/*! 红外热敏电阻驱动,用于测试体温 zn.zeng, 2021-12-02  */
#ifndef UTE_DRV_TEMPERATURE_INFRARED_THERMISTOR_SUPPORT
#define UTE_DRV_TEMPERATURE_INFRARED_THERMISTOR_SUPPORT 1
#endif
#endif

/*! 体温电源控制zn.zeng, 2021-12-02  */
#ifndef UTE_MODULE_TEMPERATURE_POWER_SUPPORT
#define UTE_MODULE_TEMPERATURE_POWER_SUPPORT 0
#endif
#if UTE_MODULE_TEMPERATURE_POWER_SUPPORT
#ifndef UTE_MODULE_TEMPERATURE_POWER_GPIO_PIN
#define UTE_MODULE_TEMPERATURE_POWER_GPIO_PIN IO_PF5
#define UTE_MODULE_TEMPERATURE_POWER_ACTION_LEVEL 0
#endif
#endif

#ifndef UTE_DRV_TEMPERATURE_INFRARED_THERMISTOR_SKIN_ADC
#define UTE_DRV_TEMPERATURE_INFRARED_THERMISTOR_SKIN_ADC ADCCH_PB2
#define UTE_DRV_TEMPERATURE_INFRARED_THERMISTOR_AMBIENT_ADC ADCCH_PB2
#endif

/*!体温测试超时时间 zn.zeng, 2021-10-22  */
#ifndef UTE_MODULE_TEMPERATURE_TEST_TIMEOUT_SECOND
#define UTE_MODULE_TEMPERATURE_TEST_TIMEOUT_SECOND 60
#endif
/*！温度模块各电阻参数*/
#ifndef UTE_DRV_INFRARED_THERMISTOR_RS
#define UTE_DRV_INFRARED_THERMISTOR_RS 330 //330K
#endif
#ifndef UTE_DRV_INFRARED_THERMISTOR_RT
#define UTE_DRV_INFRARED_THERMISTOR_RT 100 //100k
#endif
#ifndef UTE_DRV_INFRARED_THERMISTOR_RT_B
#define UTE_DRV_INFRARED_THERMISTOR_RT_B 4250  // 这个值有规格书给出，RT是10k的时候是3380k,100k的时候是4250k
#endif
#ifndef UTE_DRV_INFRARED_THERMISTOR_IS_PARALLEL
#define UTE_DRV_INFRARED_THERMISTOR_IS_PARALLEL 0 //热敏电阻是并联电路
#endif
#if UTE_DRV_INFRARED_THERMISTOR_IS_PARALLEL
#ifndef UTE_DRV_INFRARED_THERMISTOR_PARALLEL_RT
#define UTE_DRV_INFRARED_THERMISTOR_PARALLEL_RT 10 //10k并联电阻值
#endif
#endif
/*! zn.zeng, 2021-12-04  */
#ifndef UTE_MODULE_TEMPERATURE_SAVE_DATA_MAX_DAYS
#define UTE_MODULE_TEMPERATURE_SAVE_DATA_MAX_DAYS 7
#endif
/*! 体温自动测试默认关闭支持zn.zeng, 2021-12-01  */
#ifndef UTE_MODULE_TEMPERATURE_AUTO_TEST_OPEN
#define UTE_MODULE_TEMPERATURE_AUTO_TEST_OPEN      false
#define UTE_MODULE_TEMPERATURE_AUTO_TEST_INTERVAL_SECOND       600
#define UTE_MODULE_TEMPERATURE_AUTO_LIMIT_TIME_OPEN      false
#define UTE_MODULE_TEMPERATURE_AUTO_LIMIT_TIME_START_SECOND       28800//8:00
#define UTE_MODULE_TEMPERATURE_AUTO_LIMIT_TIME_STOP_SECOND       75600//21;00
#define UTE_MODULE_TEMPERATURE_WARNING_OPEN      false
#define UTE_MODULE_TEMPERATURE_WARNING_LOW_VALUE 0 // 0度
#define UTE_MODULE_TEMPERATURE_WARNING_HEIGHT_VALUE 3730 // 37.3度
#endif

/*! 在线表盘功能 casen, 2021-11-26  */
#ifndef UTE_MODULE_WATCHONLINE_SUPPORT
#define UTE_MODULE_WATCHONLINE_SUPPORT    1
#endif
#ifndef UTE_MODULE_WATCHONLINNE_COMPATIBLE_LEVEL
#define UTE_MODULE_WATCHONLINNE_COMPATIBLE_LEVEL    2
#endif
/*! 多个在线表盘功能，最大表盘个数,默认值为1，不能修改，在具体项目里面修改此值 zn.zeng, 2022-06-28  */
#ifndef UTE_MODULE_WATCHONLINE_MULTIPLE_MAX_CNT
#define UTE_MODULE_WATCHONLINE_MULTIPLE_MAX_CNT    1
#endif
/*! 多个在线表盘功能，每个表盘的起始地址组 zn.zeng, 2022-06-28  */
#ifndef UTE_MODULE_WATCHONLINE_MULTIPLE_BASE_ADDRESS_ARRAYS
#define UTE_MODULE_WATCHONLINE_MULTIPLE_BASE_ADDRESS_ARRAYS {UTE_MODULE_WATCHONLINE_START_ADDRESS}
#endif
/*! 使用UTE表盘头,需使用修改后的表盘工具生成表盘，无法使用原厂工具,wang.luo 2024-11-25 */
#ifndef UTE_MODULE_CUSTOM_WATCHONLINE_UITOOL_SUPPORT
#define UTE_MODULE_CUSTOM_WATCHONLINE_UITOOL_SUPPORT 1
#endif

/*! SOS联系人拨号功能,xjc 2022-07-06  */
#ifndef UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT
#define UTE_MODUEL_CALL_SOS_CONTACT_SUPPORT 0
#endif
/*! 最大支持SOS联系人数量,xjc 2022-07-06  */
#ifndef UTE_MODUEL_CALL_SOS_CONTACT_MAX
#define UTE_MODUEL_CALL_SOS_CONTACT_MAX 1
#endif

/*电话本名字长度扩展到40byte(unicode)*/
#ifndef UTE_MODUEL_CALL_ADDRESSBOOK_EXPANSION_LENGTH_SUPPORT
#define UTE_MODUEL_CALL_ADDRESSBOOK_EXPANSION_LENGTH_SUPPORT 1
#endif

/* 音频调试，正常模式下不能打开 zn.zeng 2022-01-10*/
#ifndef UTE_CONNECT_PC_AUDIO_TEST
#define UTE_CONNECT_PC_AUDIO_TEST 0
#endif

/*! 本地铃声音量设置(静音+音量加减) dengli.lu, 2022-04-24  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_VOLUME_SET
#define UTE_MODULE_LOCAL_RINGTONE_VOLUME_SET 1
#endif
/*! 默认本地铃声音量值 dengli.lu, 2022-04-24  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_DEFAULT_VOLUME
#define UTE_MODULE_LOCAL_RINGTONE_DEFAULT_VOLUME 12
#endif
/*! 本地铃声静音默认状态 dengli.lu, 2022-04-24  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_DEFAULT_MUTE
#define UTE_MODULE_LOCAL_RINGTONE_DEFAULT_MUTE false
#endif

/*! 娱乐声音开关支持,xjc 2022-04-27*/
#ifndef UTE_MODULE_BT_ENTERTRANMENT_VOICE_SWITCH_SUPPORT
#define UTE_MODULE_BT_ENTERTRANMENT_VOICE_SWITCH_SUPPORT 1
#endif
#ifndef UTE_MODULE_BT_ENTERTRANMENT_VOICE_DEFAULT
#define UTE_MODULE_BT_ENTERTRANMENT_VOICE_DEFAULT false
#endif

/*! 默认来电铃声都播放本地铃声 xjc, 2022-04-22  */
#ifndef UTE_MODULE_BT_RINGTONE_USE_LOCAL_RESOURCE
#define UTE_MODULE_BT_RINGTONE_USE_LOCAL_RESOURCE 1
#endif
/*! 本地铃声默认时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-04-22  */
#ifndef UTE_MODULE_BT_LOCAL_RINGTONE_DURATION
#define UTE_MODULE_BT_LOCAL_RINGTONE_DURATION 3
#endif
/*! 默认的本地铃声序号 xjc, 2022-04-19  */
#ifndef UTE_MODULE_BT_RINGTONE_HF_CALL_IN_INDEX
#define UTE_MODULE_BT_RINGTONE_HF_CALL_IN_INDEX 0X00
#endif

/*! 查找手环支持铃声播放 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_FIND_SUPPORT
#define UTE_MODULE_LOCAL_RINGTONE_FIND_SUPPORT 0
#endif
/*! 查找手环铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_FIND_DURATION
#define UTE_MODULE_LOCAL_RINGTONE_FIND_DURATION 3
#endif
/*! 查找手环铃声响铃总时长 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_FIND_TIME
#define UTE_MODULE_LOCAL_RINGTONE_FIND_TIME 30
#endif
/*! 查找手环铃声的序号 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_FIND_INDEX
#define UTE_MODULE_LOCAL_RINGTONE_FIND_INDEX 0x01
#endif

/*! 闹钟支持铃声播放 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_ALARM_SUPPORT
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_SUPPORT 0
#endif
/*! 闹钟铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_ALARM_DURATION
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_DURATION 3
#endif
/*! 闹钟铃声响铃总时长 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_ALARM_TIME
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_TIME 30
#endif
/*! 闹钟铃声的序号 xjc, 2022-05-12  */
#ifndef UTE_MODULE_LOCAL_RINGTONE_ALARM_INDEX
#define UTE_MODULE_LOCAL_RINGTONE_ALARM_INDEX 0x01
#endif

/*! 新工厂老化测试支持播放铃声,xjc 2022-05-16*/
#ifndef UTE_MODULE_NEW_FACTORY_TEST_RING_SUPPORT
#define UTE_MODULE_NEW_FACTORY_TEST_RING_SUPPORT 1
#endif
/*! 新工厂老化测试铃声时长,根据铃声长度来定，超时之后重新开始播铃声 xjc, 2022-05-16*/
#ifndef UTE_MODULE_NEW_FACTORY_TEST_RING_DURATION
#define UTE_MODULE_NEW_FACTORY_TEST_RING_DURATION 3
#endif
/*! 新工厂老化测试铃声响铃总时长 xjc, 2022-05-16  */
#ifndef UTE_MODULE_NEW_FACTORY_TEST_RING_TIME
#define UTE_MODULE_NEW_FACTORY_TEST_RING_TIME 30
#endif
/*! 新工厂老化测试铃声的序号 xjc, 2022-05-16  */
#ifndef UTE_MODULE_NEW_FACTORY_TEST_RING_INDEX
#define UTE_MODULE_NEW_FACTORY_TEST_RING_INDEX 0X01
#endif
/*! 新工厂老化测试铃声的默认音量 dengli.lu, 2022-08-03  */
#ifndef UTE_MODULE_NEW_FACTORY_TEST_RING_VOLUME_LEVEL
#define UTE_MODULE_NEW_FACTORY_TEST_RING_VOLUME_LEVEL 12
#endif

/*! 咪头喇叭测试的时候，播放音量, 2022-06-15  */
#ifndef UTE_MODULE_MIC_FACTORY_TEST_PLAY_VOLUME
#define UTE_MODULE_MIC_FACTORY_TEST_PLAY_VOLUME 10
#endif

/*! 咪头喇叭测试录音时长,wang.luo 2025-05-10 */
#ifndef UTE_MODULE_MIC_FACTORY_TEST_RECORDING_TIME
#define UTE_MODULE_MIC_FACTORY_TEST_RECORDING_TIME 3
#endif

/*! hardfault info to flash zn.zeng,2022-03-10*/
#if UTE_MODULE_LOG_SUPPORT
#define UTE_HARDFAULT_INFO_TO_FLASH_SUPPORT 0
#else
#define UTE_HARDFAULT_INFO_TO_FLASH_SUPPORT 1
#endif

/*! 保存重启信息最大数量,wang.luo 2024-12-30 */
#ifndef UTE_HARDFAULT_INFO_TO_FLASH_MAX_CNT
#define UTE_HARDFAULT_INFO_TO_FLASH_MAX_CNT 6
#endif

/*! 重置BT地址，启用后BT和BLE地址会不同,wang.luo 2025-02-08 */
#ifndef UTE_MODULE_BT_CHANGE_MAC_SUPPORT
#define UTE_MODULE_BT_CHANGE_MAC_SUPPORT 1
#endif

/*! 是否创建1S定时器，用于计时和每秒钟任务，反之使用系统500ms任务执行，wang.luo 2024-12-30 */
#ifndef UTE_MODULE_CREATE_SYS_1S_TIMER_SUPPORT
#define UTE_MODULE_CREATE_SYS_1S_TIMER_SUPPORT 1
#endif

/*! PWRKEY,wang.luo 2024-12-03 */
#ifndef UTE_DRV_PWRKEY_SUPPORT
#define UTE_DRV_PWRKEY_SUPPORT 1
#endif

/*! ADKEY,wang.luo 2024-12-03 */
#ifndef UTE_DRV_ADCKEY_SUPPORT
#define UTE_DRV_ADCKEY_SUPPORT 0
#endif

/*! IOKEY,wang.luo 2024-12-03 */
#ifndef UTE_DRV_IOKEY_SUPPORT
#define UTE_DRV_IOKEY_SUPPORT 0
#endif

#if UTE_DRV_PWRKEY_SUPPORT
/*! PWRKEY按键最大数量,wang.luo 2024-12-03 */
#ifndef UTE_DRV_PWRKEY_MAX_CNT
#define UTE_DRV_PWRKEY_MAX_CNT 1
#elif (UTE_DRV_PWRKEY_MAX_CNT > 5)
#error "UTE_DRV_PWRKEY_MAX_CNT must be less than 5"
#endif
#if (UTE_DRV_PWRKEY_MAX_CNT > 0)
#ifndef UTE_DRV_PWRKEY_KEY0
#define UTE_DRV_PWRKEY_KEY0 KEY_BACK
#define UTE_DRV_PWRKEY_KEY0_MAX_ADC 0x08 // 0R
#endif
#else
#define UTE_DRV_PWRKEY_KEY0 NO_KEY
#define UTE_DRV_PWRKEY_KEY0_MAX_ADC 0x08 // 0R
#endif
#if (UTE_DRV_PWRKEY_MAX_CNT > 1)
#ifndef UTE_DRV_PWRKEY_KEY1
#define UTE_DRV_PWRKEY_KEY1 KEY_LEFT
#define UTE_DRV_PWRKEY_KEY1_MAX_ADC 0x3A // 12K
#endif
#else
#define UTE_DRV_PWRKEY_KEY1 NO_KEY
#define UTE_DRV_PWRKEY_KEY1_MAX_ADC 0x3A // 12K
#endif
#if (UTE_DRV_PWRKEY_MAX_CNT > 2)
#ifndef UTE_DRV_PWRKEY_KEY2
#define UTE_DRV_PWRKEY_KEY2 KEY_RIGHT
#define UTE_DRV_PWRKEY_KEY2_MAX_ADC 0x7B // 47K
#endif
#else
#define UTE_DRV_PWRKEY_KEY2 NO_KEY
#define UTE_DRV_PWRKEY_KEY2_MAX_ADC 0x7B // 47K
#endif
#if (UTE_DRV_PWRKEY_MAX_CNT > 3)
#ifndef UTE_DRV_PWRKEY_KEY3
#define UTE_DRV_PWRKEY_KEY3 KEY_VOL_UP
#define UTE_DRV_PWRKEY_KEY3_MAX_ADC 0xCB // 200K
#endif
#else
#define UTE_DRV_PWRKEY_KEY3 NO_KEY
#define UTE_DRV_PWRKEY_KEY3_MAX_ADC 0xCB // 200K
#endif
#if (UTE_DRV_PWRKEY_MAX_CNT > 4)
#ifndef UTE_DRV_PWRKEY_KEY4
#define UTE_DRV_PWRKEY_KEY4 KEY_VOL_DOWN
#define UTE_DRV_PWRKEY_KEY4_MAX_ADC 0xFF
#endif
#else
#define UTE_DRV_PWRKEY_KEY4 NO_KEY
#define UTE_DRV_PWRKEY_KEY4_MAX_ADC 0xFF
#endif
#endif



#endif//_UTE_PROJECT_CONFIG_H_
